#!/usr/bin/env bash
# Creates .env.local for local development. That file is gitignored — never commit it.
set -euo pipefail
cd "$(dirname "$0")"
ENV_FILE=".env.local"

if [ -f "$ENV_FILE" ]; then
  printf 'A %s already exists. Overwrite? [y/N] ' "$ENV_FILE"
  read -r reply
  case "$reply" in [yY]*) ;; *) echo "Kept existing file."; exit 0 ;; esac
fi

printf 'Gemini API key (hidden; press Enter to skip and stay in Demo Mode): '
read -rs GEMINI_KEY
printf '\n'

printf 'Gemini model [gemini-2.5-flash]: '
read -r GEMINI_MODEL
GEMINI_MODEL="${GEMINI_MODEL:-gemini-2.5-flash}"

umask 077
cat > "$ENV_FILE" <<EOF
# Generated by setup-env.sh — do not commit.
# Vite inlines every VITE_* var into the client bundle, so this key is readable
# by anyone who loads a deployed build. Use a restricted key, or proxy through
# a backend before putting this in front of real users.
VITE_GEMINI_API_KEY=$GEMINI_KEY
VITE_GEMINI_MODEL=$GEMINI_MODEL
EOF
chmod 600 "$ENV_FILE"

if [ -n "$GEMINI_KEY" ]; then
  echo "Wrote $ENV_FILE (key set — live Gemini calls enabled)."
else
  echo "Wrote $ENV_FILE (no key — app runs in Demo Mode with local synthesis)."
fi
